export const projects = [
    {
        id: 1,
        isFeatured: true,
        title: 'Oral Cancer Classification using Neural Networks',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A machine learning model that detects and classifies oral cancer from images, using preprocessing, feature extraction, and evaluation techniques.',
        tags: ['Python', 'Javascript', 'React'],
        projectType: 'Machine Learning',
        statusOrCategory: 'Research Project',
        sourceCodeUrl: '#',
        accomplishments: [
            "Engineered a convolutional neural network (CNN) to classify oral cancer from medical imagery with high accuracy.",
            "Implemented advanced image preprocessing and feature extraction techniques to improve model performance.",
            "Validated the model's effectiveness using comprehensive evaluation metrics, contributing to advancements in early cancer detection.",
        ],
    },
    {
        id: 2,
        isFeatured: true,
        title: 'Personal Portfolio',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A responsive portfolio website designed to showcase personal projects, skills, and achievements with a clean and modern layout.',
        tags: ['HTML', 'CSS', 'Javascript'],
        projectType: 'Portfolio Website',
        statusOrCategory: 'Personal Project',
        sourceCodeUrl: '#',
        accomplishments: [
            "Designed and developed a fully responsive portfolio website using modern HTML, CSS, and JavaScript.",
            "Created a clean and intuitive user interface to effectively showcase projects, skills, and achievements.",
            "Optimized website performance for fast load times and a seamless user experience across all devices.",
        ],
    },
    {
        id: 3,
        isFeatured: true,
        title: 'E-commerce Platform',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A full-stack e-commerce site featuring product listings, user accounts, shopping cart functionality, and secure online payment integration.',
        tags: ['Node.js', 'Express', 'MongoDB'],
        projectType: 'Web Application',
        statusOrCategory: 'Client Work',
        sourceCodeUrl: '#',
        accomplishments: [
            "Built a complete full-stack e-commerce platform using the MERN stack (MongoDB, Express, React, Node.js).",
            "Integrated a secure payment gateway for seamless and safe online transactions.",
            "Developed core features including user authentication, product management, and a dynamic shopping cart.",
        ],
    },
    {
        id: 4,
        isFeatured: true,
        title: 'Task Management App',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A collaborative web app that helps users manage tasks, organize projects, and track progress across different teams and devices.',
        tags: ['React', 'Firebase', 'TailwindCSS'],
        projectType: 'Productivity App',
        statusOrCategory: 'Open Source',
        sourceCodeUrl: '#',
        accomplishments: [
            "Developed a real-time, collaborative task management application using React and Firebase.",
            "Implemented features for project organization, task assignment, and progress tracking to enhance team productivity.",
            "Designed a responsive and user-friendly interface with TailwindCSS for a consistent experience on all devices.",
        ],
    },
    {
        id: 5,
        isFeatured: false,
        title: 'Weather Forecast Dashboard',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A dashboard that fetches live weather data from an API, providing detailed forecasts, temperature trends, and location-based updates.',
        tags: ['Javascript', 'API', 'Bootstrap'],
        projectType: 'Dashboard',
        statusOrCategory: 'Personal Project',
        sourceCodeUrl: '#',
        accomplishments: [
            "Created a dynamic weather dashboard that provides real-time forecasts by integrating a third-party weather API.",
            "Implemented location-based services to deliver personalized weather updates.",
            "Designed a clean UI with Bootstrap to visualize weather data, including temperature trends and forecasts.",
        ],
    },
    {
        id: 6,
        isFeatured: false,
        title: 'Chat Application',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A real-time chat platform with private rooms, group messaging, and media sharing powered by WebSockets for instant communication.',
        tags: ['Socket.io', 'Node.js', 'React'],
        projectType: 'Real-Time App',
        statusOrCategory: 'MVP',
        sourceCodeUrl: '#',
        accomplishments: [
            "Engineered a real-time chat application using Node.js, React, and Socket.io for instant messaging.",
            "Implemented key features such as private rooms, group chats, and media file sharing.",
            "Ensured low-latency communication by leveraging WebSocket technology for persistent, two-way connections.",
        ],
    },
    {
        id: 7,
        isFeatured: false,
        title: 'Blog Platform',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A blogging system with markdown support, comments, and user profiles, allowing easy content publishing and interaction with readers.',
        tags: ['Laravel', 'PHP', 'MySQL'],
        projectType: 'Content Platform',
        statusOrCategory: 'Client Work',
        sourceCodeUrl: '#',
        accomplishments: [
            "Developed a full-featured blog platform using the Laravel framework, PHP, and MySQL.",
            "Integrated a Markdown editor for streamlined content creation and a commenting system for reader engagement.",
            "Built a complete user management system with profiles, roles, and permissions.",
        ],
    },
    {
        id: 8,
        isFeatured: false,
        title: 'Stock Price Tracker',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'An application for monitoring stock prices in real time, visualizing market trends, and saving custom watchlists for quick access.',
        tags: ['Python', 'Flask', 'Chart.js'],
        projectType: 'Finance Tool',
        statusOrCategory: 'Side Project',
        sourceCodeUrl: '#',
        accomplishments: [
            "Built a real-time stock price tracking application using Python and Flask.",
            "Integrated financial data APIs to fetch live stock market data and historical trends.",
            "Implemented data visualization using Chart.js to create interactive charts for monitoring market performance.",
        ],
    },
    {
        id: 9,
        isFeatured: false,
        title: 'Fitness Tracker',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A mobile-friendly app that tracks workouts, calories, and personal goals, giving users insights to improve their health journey.',
        tags: ['React Native', 'Expo', 'SQLite'],
        projectType: 'Mobile App',
        statusOrCategory: 'Personal Project',
        sourceCodeUrl: '#',
        accomplishments: [
            "Developed a cross-platform mobile fitness tracking application using React Native and Expo.",
            "Implemented local data storage with SQLite for offline access to workout history and goals.",
            "Designed an intuitive interface for users to log workouts, track calories, and visualize their fitness progress.",
        ],
    },
    {
        id: 10,
        isFeatured: false,
        title: 'Online Learning Platform',
        timeline: 'Jan 2023 - Feb 2025',
        image: '/images/placeholder_project_management.avif',
        into: 'A platform for hosting online courses with video lessons, progress tracking, and interactive quizzes for engaging learning experiences.',
        tags: ['Django', 'Python', 'PostgreSQL'],
        projectType: 'EdTech Platform',
        statusOrCategory: 'Open Source',
        sourceCodeUrl: '#',
        accomplishments: [
            "Constructed a robust online learning platform using Django, Python, and PostgreSQL.",
            "Developed core functionalities including course creation, video lesson hosting, and student progress tracking.",
            "Implemented an interactive quiz system to assess learning and enhance user engagement.",
        ],
    },
];