export const devSkills = [
    {
        name: 'Bootstrap',
        devIcon: 'devicon-bootstrap-plain',
        proficiency: 82,
        background: 'sky-200',
    },
    {
        name: 'JavaScript',
        devIcon: 'devicon-javascript-plain',
        proficiency: 67,
        background: 'blue-200',
    },
    {
        name: 'TypeScript',
        devIcon: 'devicon-typescript-plain',
        proficiency: 91,
        background: 'amber-200',
    },
    {
        name: 'React',
        devIcon: 'devicon-react-original',
        proficiency: 56,
        background: 'lime-200',
    },
    {
        name: 'Vue.js',
        devIcon: 'devicon-vuejs-plain',
        proficiency: 74,
        background: 'rose-200',
    },
    {
        name: 'Angular',
        devIcon: 'devicon-angularjs-plain',
        proficiency: 39,
        background: 'sky-200',
    },
    {
        name: 'Node.js',
        devIcon: 'devicon-nodejs-plain',
        proficiency: 83,
        background: 'yellow-200',
    },
    {
        name: 'Express',
        devIcon: 'devicon-express-original',
        proficiency: 61,
        background: 'emerald-200',
    },
    {
        name: 'PHP',
        devIcon: 'devicon-php-plain',
        proficiency: 72,
        background: 'orange-200',
    },
    {
        name: 'Laravel',
        devIcon: 'devicon-laravel-plain',
        proficiency: 46,
        background: 'cyan-200',
    },
    {
        name: 'Python',
        devIcon: 'devicon-python-plain',
        proficiency: 95,
        background: 'pink-200',
    },
    {
        name: 'Django',
        devIcon: 'devicon-django-plain',
        proficiency: 64,
        background: 'lime-200',
    },
    {
        name: 'Ruby',
        devIcon: 'devicon-ruby-plain',
        proficiency: 52,
        background: 'sky-200',
    },
    {
        name: 'Rails',
        devIcon: 'devicon-rails-plain',
        proficiency: 87,
        background: 'cyan-200',
    },
    {
        name: 'Java',
        devIcon: 'devicon-java-plain',
        proficiency: 79,
        background: 'emerald-200',
    },
    {
        name: 'Spring',
        devIcon: 'devicon-spring-plain',
        proficiency: 43,
        background: 'pink-200',
    },
    {
        name: 'C#',
        devIcon: 'devicon-csharp-plain',
        proficiency: 66,
        background: 'amber-200',
    },
    {
        name: 'Docker',
        devIcon: 'devicon-docker-plain',
        proficiency: 90,
        background: 'lime-200',
    },
    {
        name: 'Kubernetes',
        devIcon: 'devicon-kubernetes-plain',
        proficiency: 58,
        background: 'amber-200',
    },
    {
        name: 'MongoDB',
        devIcon: 'devicon-mongodb-plain',
        proficiency: 84,
        background: 'violet-200',
    },
];
